# Generated by Django 3.0.3 on 2021-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('GATE', 'GATE'), ('JEE', 'JEE'), ('NEET', 'NEET')], default='GATE', max_length=20)),
                ('Category', models.CharField(choices=[('Civil Engineering (CE)', 'Civil Engineering (CE)'), ('Chemical Engineering (CH)', 'Chemical Engineering (CH)'), ('Computer Science and Information Technology (CS)', 'Computer Science and Information Technology (CS)'), ('Electrical Engineering (EE)', 'Electrical Engineering (EE)')], default='', max_length=100)),
                ('Year', models.IntegerField(default=0)),
                ('Part', models.IntegerField(default=1)),
                ('Paper', models.FileField(blank=True, null=True, upload_to='previous_papers/')),
            ],
        ),
    ]
