# Generated by Django 3.0.3 on 2021-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_paper',
            name='Name',
            field=models.CharField(choices=[('GATE', 'GATE'), ('JEE', 'JEE'), ('NEET', 'NEET')], default='gate', max_length=20),
        ),
    ]
