# Generated by Django 3.0.3 on 2021-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211017_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_paper',
            name='Category',
            field=models.CharField(choices=[('', ''), ('Civil Engineering (CE)', 'Civil Engineering (CE)'), ('Chemical Engineering (CH)', 'Chemical Engineering (CH)'), ('Computer Science and Information Technology (CS)', 'Computer Science and Information Technology (CS)'), ('Electrical Engineering (EE)', 'Electrical Engineering (EE)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='previous_paper',
            name='Name',
            field=models.CharField(choices=[('GATE', 'GATE'), ('JEE', 'JEE'), ('NEET', 'NEET')], max_length=20),
        ),
    ]
