# Generated by Django 3.0.3 on 2021-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211017_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_paper',
            name='Name',
            field=models.CharField(choices=[('GATE', 'GATE'), ('JEE', 'JEE'), ('NEET', 'NEET')], default='GATE', max_length=20),
        ),
    ]
