# Generated by Django 3.0.3 on 2021-10-19 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211017_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_paper',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
