# Generated by Django 3.0.3 on 2021-10-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='json',
        ),
    ]
