# Generated by Django 3.0.3 on 2021-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20211108_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jee',
            name='Name',
            field=models.CharField(default='20', max_length=200),
        ),
        migrations.AlterField(
            model_name='neet',
            name='Name',
            field=models.CharField(default='20', max_length=200),
        ),
    ]
